# -*- coding: utf-8 -*-
"""Substraction_streamlit.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oyKJFhE5dGqZ1nmkjNUHWkF8FaPrUvXT
"""

import streamlit as st
st.title ('Subtraction  of two Numbers')
num1=st.number_input('First NUmber',format="%g")
num2=st.number_input('Second NUmber',format="%g")
difference=num1-num2
if st.button('Subtract'):
  st.write('({})-({}))={}'.format(num1,num2,difference))
  st.write('Subtraction of numbers {} and {} is equal to{}'.format(num1,num2,difference))
